defaultProject: project-d2e743fd-f7fe-4894-a24
defaultLocation: europe-west1
defaultDataset: curated
defaultAssertionDataset: dataform_assertions
vars:
  gcsBucket: home_assignments
  gcsPrefix: data
